language: node_js
node_js:
- 6
- 8
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: me@mikakalathil.ca
  api_key:
    secure: M+SrtYGQo5DsnepJqEwuy5e7K6Ct/dxwc26AM/1DDjUP3DKCTi4YyWqAEhivIr9p++raeEn6AqJKVbY81gfotDdSEHtiFRVN3NmWcPf9dUD1oyOtIJ9bKI+GdeRx+O11265JlJ2V0d+WZMgZVazWOJ2tjhb3hqxyoH559hYqsWKQejRDlNhu1mFROCFDUFCJESS39v0V0peCbtYlpjLAF8x25rbrq0I9Er5OLIOR2E4QhW8SgO64yHDEXJfdUXYV69Ycew4mdA2FRmLBYq+Q5UMjeHxYUwJ/hBQw6j/1szRiH9/J0OqBUmMautSwYGSSEzeiI8/R0EXq9lCHDB01Q4sJTt2oXYBgIABB4Tg8M8fZnMpboZUsujLRnUo1bmAqVHXJTOQSzJSDI3qMvzcpxP0JG5f+ldwiDgvn38uLfBgH6c0mbmFZUUuSGOQQpF/WnSc3KABg3/1U/e4SPX8V7Znx4W4O/c3gXuYvRbwzI6V1AVHBfb8GlNaGitutNMwBPqBnl8KU0VEOH7MCdwWjEAozz2SJHEBG3RkxEqkxPj2R+XXoTRiZdLE3JZUHoYKgaBa8Tv1BcA1logn12eX2DcouZGh+0P88Ka+jsJaCtdgHrdMH3rIl2JtfOw1zaV0qHTuLKJ4U1u1fzqSfdG5ZMuk0QtwTTD6ZjWEtw+EqOMs=
  on:
    tags: true
    repo: MikaAK/s3-plugin-webpack
env:
  global:
  - secure: go5xplgZxlUh7+zIv7SkBKb0/FK/JPwa51Z0ddG+BzGd5MHqKBre1Fwlc0DAY+3wkb+1HrgpdW9GJNyU/jojG45hzTM0+2U6aL/YshL/r8Zy9bI7OM1ScT36hiNm/5BCa1oOswc3yGpsA8whitsPdHPmpAf34ZPsfGI3I8CBaL5COuFQgXcTglv/7Tdw5WtLCDJhQLz+2LvrhTuwbsYunXD7O6nUdHJGWN3RcvlimC8PU4zbK6Xnd1vi3eQgcnyupTGohT1FFjjq2ihSz6cwM94i707L2RaqHS/go8bqwH8a7KuCE96sW6mQ6pAubn3xxuL/PUsKeIHLVCAekEJTYRcjL7n6J2R7N6xa38alkwaG6GIiLVTAC5VfrjV5lmjrqTSIX29sF+ehW9qX3jPQZvQ5BDtfQlZENl89Akpva6JJCW40n/9qAdMs2EhUuw0JvPEuixIYT/p8nTo7viZVYuCW9qprWYvyJDenTOZ9dHDj0+8vMWiFGdxCjCitgjXUsOwWk4zsMoHdr35A/jYOMTz24LKtV+/c4uulYU/AfJRvQR4wK/4RwEOSS8KUcXLFXDyXjR864FVfAaZgAnb26NzvboMF2rPQBPL+48cftKwvnqtcRDjI+lI2VQUm1hiI8jkuZnTj3OG9sRyOFuQVfvopxvfKhJztmKM4b3bKono=
  - secure: AD9yd0tnNSLxlV/BHcJzEN5eqNa0E/Qko3zNCxuE0CLy3dm4nrGczmp6uaL5lwsdjjicdPo/v4s3+eRdEyrLlMGBp5EnL5TBJFaUG9ZfPe4FnLcATxqyKdQFQn1O3G7M2FI5XBe+cu3YmuZxg8WsVZzPoPzYnDGCsbOGOna4qpHb8KpTI5+a3IugJAeqXAqLWVJl1rrwbLJap0t08Ko9iHk+x5LSeb3P6QVfNmHjrf9u2NJz0zciSK6861cuQ2fkmc0J6cqLIsjkXPvSv7WOgHLnXgKWRSg6uwCEUK2BAFAQjzm6XU4XqD8f3Kbs3NpWdnTDFqdDQaWv52spZqEOx6SAITepXgP49BBa6KY1w58D8lh8od/2hlYY0QMM6xF1i1hGZt9zerkMHV1Dykkog5+9g6bWJOkJTLOOi1fGy7HBi7PUZFJN3uAIau8FvuKhFF7QLuxf4bhfgOv3+6UHkWdkKaSbDopvsa7zv+L/yZ/EZyGsT4EqX8QODREvtM0ZMb/1Os2haqqeOuhMcKoIuV0crCR6Vg6RXSVrw0E0/tSIOxkkdVZvrt3kCRdlKacu6ENeCU7eov5kIFoGjew2xZLmofBFa0zc0c7TuRsm7qUBQWeHENDToSreFRzgqDFgTQpZToSUEKHT4EP9VKRyKcaVVsMks6fS7H0Uzj6zSC0=
